  spring:
    security:
      oauth2:
        client:
          registration:
            google:
            #this is for mini-share-market-advisor project
            
              clientId: 791044062022-975gn1dts41ijrst0voad7jjcue1te92.apps.googleusercontent.com
              clientSecret : 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
              redirectUri: https://mini-share-market-advisor.uc.r.appspot.com/login/oauth2/code/google
              
             
               #clientId: 1070735995772-vb5tm664jk5gpflb1b6vetkctn77tfgn.apps.googleusercontent.com
               #clientSecret : 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
                           
  server:
    port : 8080
    #port: 9191
              